services:
  db:
    image: postgres:latest
    container_name: psql_container
    environment:
      POSTGRES_USER: anant
      POSTGRES_PASSWORD: anant
    ports:
      - '5400:5432'
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
